# packages.ini
# Created by auto-penguin-setup
#
# You can customize this file to add or remove packages as per your requirements.
# Make sure to check the pkgmap.ini file for third-party repository handling (AUR/COPR/Flatpak).
#

[core]
curl, wget # download tools
ufw # firewall tool
gnome-keyring
ttf-jetbrains-mono-nerd
ttf-nerd-fonts-symbols-mono
terminus-font
xclip # clipboard-tool

[apps]
evince # pdf viewer
chromium
easyeffects
lsp-plugins # easyeffects dependency
seahorse    # GNOME keyring manager gui
xournalpp   # note taking application
rnote       # note taking application
keepassxc   # password manager
pavucontrol # advanced volume control
borgbackup  # backup tools
python-pyfuse3 # depenency for borgbackup
syncthing # file synchronization tool
syncthingtray # tray application for syncthing
obsidian
signal
zed
spotify
ncspot   # An ncurses Spotify client written in Rust using librespot
# for electron apps
# Interface for userspace programs to export a filesystem to the Linux kernel
fuse2
# editors
neovim, vim
# terminal emulators
alacritty, xterm

[dev]
tmux # terminal multiplexer
# development dbus headers
dbus-devel
trash-cli # trashing tool, alternative to rm
tealdeer # community-driven documentation for command-line utilities
# tools for hardware monitoring
lm_sensors,htop,btop
# git and github tools
lazygit,git-credential-libsecret,gh
# shell utilities and enhancements
starship # customizable prompt for any shell
zoxide   # smarter cd
eza      # ls alternative
fd-find  # find alternative
bat      # cat alternative
fzf      # fuzzy finder
zsh-syntax-highlighting,zsh-autosuggestions
# languages
zsh,luarocks,cargo,yarnpkg,python3-devel,pip
# language servers and formatters
shfmt,shellcheck
bash-language-server
ruff # python linter
jq # json processor
marked # A markdown parser built for speed (for doom emacs)

[desktop]
# for virtual machines
virt-manager,libvirt,qemu-base,virt-install
# for benchmarking
sysbench, s-tui
# hardware management tools: corsair, logitech
ckb-next,solaar

[laptop]
brightnessctl # screen brightness control
powertop # power consumption monitoring
thinkfan # laptop fan control
acpi # advanced configuration and power interface
tlp # Linux advanced power management

[homeserver]
fail2ban # intrusion prevention

[qtile]
python-xlib # X11 library for Python
qtile-extras # additional widgets and layouts for qtile
python3-dbus-fast # qtile-extras dependency

[i3]
polybar,i3

[wm-common]
xdotool
nm-applet # network manager applet
i3lock # simple screen locker
rofi # application launcher
lxappearance # for theming
gammastep # blue light filter
numlockx # enable numlock on startup
dunst # notification daemon
flameshot # screenshot tool
playerctl # media player controller
xev #  tool to monitor X11 events
xset #  tool to set X11 properties
feh # wallpaper setter
picom # compositor
thunar # file manager
ncdu # Size analyzer tool
xfce4-power-manager
# display manager(currently lightdm broken and also it won't suport rootless Xorg)
gdm

#TODO: for steam and similar gaming stuff need to enable multilib repo on arch
# and other specific stuff on other distros.
# So, this section is still work in progress.
[games]
wine

