[general]
temp-day=6000
temp-night=2700
adjustment-method=randr
location-provider=manual
brightness-day=1
brightness-night=0.7
dawn-time=08:00
dusk-time=18:00
#NOTE: Below are the manual settings for latitude and longitude.
[manual]
; lat=41
; lon=28
