return {
  --NOTE: Disabled for now which I mainly use zed editor
  --
  -- "zbirenbaum/copilot.lua",
  -- cmd = "Copilot",
  -- build = ":Copilot auth",
  -- event = "BufReadPost",
  -- lazy = true,
  -- opts = {
  --   suggestion = {
  --     enabled = not vim.g.ai_cmp,
  --     auto_trigger = true,
  --     hide_during_completion = vim.g.ai_cmp,
  --     --NOTE: seems like this is tempature and not allowed on raptor-mini model
  --     -- debounce = 75, -- Seems like latency for suggestions
  --     keymap = {
  --       accept = false, -- handled by nvim-cmp / blink.cmp
  --       next = "<M-]>",
  --       prev = "<M-[>",
  --     },
  --   },
  --   panel = { enabled = false, auto_refresh = true },
  --   copilot_model = "gpt-5-mini", -- gpt-4o-copilot, claude-3.5-sonnet, claude-3-opus, claude-3-haiku
  --   filetypes = {
  --     yaml = false,
  --     markdown = false,
  --     help = false,
  --     gitcommit = true,
  --     gitrebase = false,
  --     hgcommit = false,
  --     svn = false,
  --     cvs = false,
  --     ["."] = false,
  --   },
  --   workspace_folders = {
  --     "/home/developer/Documents/my-repos/",
  --     "/home/developer/Documents/global-repos/",
  --   },
  -- },
  -- -- add ai_accept action
  -- {
  --   "zbirenbaum/copilot.lua",
  --   opts = function()
  --     LazyVim.cmp.actions.ai_accept = function()
  --       if require("copilot.suggestion").is_visible() then
  --         LazyVim.create_undo()
  --         require("copilot.suggestion").accept()
  --         return true
  --       end
  --     end
  --   end,
  -- },
  --
  -- -- -- lualine
  -- -- {
  -- --   "nvim-lualine/lualine.nvim",
  -- --   optional = true,
  -- --   event = "VeryLazy",
  -- --   opts = function(_, opts)
  -- --     table.insert(
  -- --       opts.sections.lualine_x,
  -- --       2,
  -- --       LazyVim.lualine.status(LazyVim.config.icons.kinds.Copilot, function()
  -- --         local clients = package.loaded["copilot"] and LazyVim.lsp.get_clients({ name = "copilot", bufnr = 0 }) or {}
  -- --         if #clients > 0 then
  -- --           local status = require("copilot.api").status.data.status
  -- --           return (status == "InProgress" and "pending") or (status == "Warning" and "error") or "ok"
  -- --         end
  -- --       end)
  -- --     )
  -- --   end,
  -- -- },
  --
  -- vim.g.ai_cmp
  --     and {
  --       {
  --         "saghen/blink.cmp",
  --         optional = true,
  --         dependencies = { "giuxtaposition/blink-cmp-copilot" },
  --         opts = {
  --           sources = {
  --             default = { "copilot" },
  --             providers = {
  --               copilot = {
  --                 name = "copilot",
  --                 module = "blink-cmp-copilot",
  --                 kind = "Copilot",
  --                 score_offset = 100,
  --                 async = true,
  --               },
  --             },
  --           },
  --         },
  --       },
  --     }
  --   or nil,
}
