return {
  ----NOTE: this is optional outline support for edgy.nvim
  --{
  --  "folke/edgy.nvim",
  --  optional = true,
  --  opts = function(_, opts)
  --    local edgy_idx = LazyVim.plugin.extra_idx("ui.edgy")
  --    local symbols_idx = LazyVim.plugin.extra_idx("editor.outline")
  --
  --    if edgy_idx and edgy_idx > symbols_idx then
  --      LazyVim.warn(
  --        "The `edgy.nvim` extra must be **imported** before the `outline.nvim` extra to work properly.",
  --        { title = "LazyVim" }
  --      )
  --    end
  --
  --    opts.right = opts.right or {}
  --    table.insert(opts.right, {
  --      title = "Outline",
  --      ft = "Outline",
  --      pinned = true,
  --      open = "Outline",
  --    })
  --  end,
  --},

  -- {
  --   "folke/edgy.nvim",
  --   event = "VeryLazy",
  --   init = function()
  --     vim.opt.laststatus = 3
  --     vim.opt.splitkeep = "screen"
  --   end,
  --   opts = {
  --     bottom = {
  --       -- toggleterm / lazyterm at the bottom with a height of 40% of the screen
  --       {
  --         ft = "toggleterm",
  --         size = { height = 0.4 },
  --         -- exclude floating windows
  --         filter = function(buf, win)
  --           return vim.api.nvim_win_get_config(win).relative == ""
  --         end,
  --       },
  --       {
  --         ft = "lazyterm",
  --         title = "LazyTerm",
  --         size = { height = 0.4 },
  --         filter = function(buf)
  --           return not vim.b[buf].lazyterm_cmd
  --         end,
  --       },
  --       "Trouble",
  --       { ft = "qf", title = "QuickFix" },
  --       {
  --         ft = "help",
  --         size = { height = 20 },
  --         -- only show help buffers
  --         filter = function(buf)
  --           return vim.bo[buf].buftype == "help"
  --         end,
  --       },
  --       { ft = "spectre_panel", size = { height = 0.4 } },
  --     },
  --     left = {
  --       -- Neo-tree filesystem always takes half the screen height
  --       {
  --         title = "Neo-Tree",
  --         ft = "neo-tree",
  --         filter = function(buf)
  --           return vim.b[buf].neo_tree_source == "filesystem"
  --         end,
  --         size = { height = 0.5 },
  --       },
  --       {
  --         title = "Neo-Tree Git",
  --         ft = "neo-tree",
  --         filter = function(buf)
  --           return vim.b[buf].neo_tree_source == "git_status"
  --         end,
  --         pinned = true,
  --         collapsed = true, -- show window as closed/collapsed on start
  --         open = "Neotree position=right git_status",
  --       },
  --       {
  --         title = "Neo-Tree Buffers",
  --         ft = "neo-tree",
  --         filter = function(buf)
  --           return vim.b[buf].neo_tree_source == "buffers"
  --         end,
  --         pinned = true,
  --         collapsed = true, -- show window as closed/collapsed on start
  --         open = "Neotree position=top buffers",
  --       },
  --       {
  --         title = function()
  --           local buf_name = vim.api.nvim_buf_get_name(0) or "[No Name]"
  --           return vim.fn.fnamemodify(buf_name, ":t")
  --         end,
  --         ft = "Outline",
  --         pinned = true,
  --         open = "SymbolsOutlineOpen",
  --       },
  --       -- any other neo-tree windows
  --       "neo-tree",
  --     },
  --   },
  -- },
}
