# Laptop i3 specific configuration

## EXECUTABLES
exec --no-startup-id /usr/bin/blueman-applet &
exec flatpak run io.github.martchus.syncthingtray --wait &

## KEYBINDINGS
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl set +5%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 5%-

## New two monitor workspace handling
exec ~/.local/share/linux-system-utils/display/laptop_working_asus.sh

# Dual monitor workspace configuration
workspace 1 output eDP-1
workspace 2 output HDMI-1
workspace 3 output HDMI-1
workspace 4 output eDP-1
workspace 5 output eDP-1
workspace 6 output HDMI-1

# Optional: Keybindings specific to dual monitor setup
bindsym Mod4+Shift+d move workspace to output right
bindsym Mod4+Shift+a move workspace to output left

# Cycle groups in output
# Example: you cycle only on the focused output like 1-2-3 on hdmi
# 4-5-6 on the edp-1
# bindsym Mod4+Tab workspace next_on_output
# bindsym Mod4+Shift+Tab workspace prev_on_output

bindsym Mod4+Tab exec --no-startup-id ~/.config/i3/scripts/i3-cycle-forward-output.sh
bindsym Mod4+Shift+Tab exec --no-startup-id ~/.config/i3/scripts/i3-cycle-backward-output.sh
