# Desktop specific i3 configuration

exec keepassxc &
exec ~/Applications/super-productivity.AppImage &
exec --no-startup-id ckb-next --background &
exec flatpak run io.github.martchus.syncthingtray --wait &
#NOTE: only locks not work when screen off
#TODO: find a way to lock screen via i3lock?
exec_always --no-startup-id xfce4-power-manager
